export default function PrivacyPolicyPage() {
  return (
    <div className="max-w-[800px] mx-auto py-12 px-4">
      <h1 className="mb-2 text-2xl font-semibold text-[#1a1a1a]">Privacy Policy</h1>
      <p className="mb-8 text-xs text-[#a8a29e]">Last updated: [fill in date of publishing]</p>

      <div className="space-y-6 text-sm leading-relaxed text-[#57534e] sm:text-base">
        <p>
          Balaka is a language-learning reading service provided by Oleksandr Zlydennyi
          (&quot;Balaka&quot;, &quot;we&quot;, &quot;our&quot;, or &quot;us&quot;), an individual
          operating from Spain. This Privacy Policy explains what personal data we collect when
          you use Balaka, why we collect it, and what rights you have over it.
        </p>
        <p>
          We&apos;re not a large company with a dedicated legal team — Balaka is currently a
          one-person project. We&apos;ve written this policy in plain language on purpose, and we
          try to only collect what we actually need to run the service.
        </p>

        <section>
          <h2 className="mb-2 text-lg font-medium text-[#1a1a1a]">1. Who is responsible for your data</h2>
          <p>
            Oleksandr Zlydennyi, an individual based in Spain, is the data controller for the
            personal data described in this policy.
          </p>
          <ul className="mt-3 space-y-1">
            <li>Tax ID (NIF/NIE): <span className="text-[#a8a29e]">[to be added once registered as autónomo in Spain]</span></li>
            <li>Contact email: <span className="text-[#a8a29e]">[to be added]</span></li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-[#1a1a1a]">2. What data we collect</h2>
          <p className="mb-3">
            <strong className="text-[#1a1a1a]">Account data.</strong> When you register, we
            collect your email address and password. Your password is handled by our
            authentication provider (Supabase Auth) and is never stored or seen by us in plain text.
          </p>
          <p className="mb-3">
            <strong className="text-[#1a1a1a]">Language preferences.</strong> The language
            you&apos;re learning and your native language, so we can show translations correctly.
          </p>
          <p className="mb-3">
            <strong className="text-[#1a1a1a]">Content you upload.</strong> If you upload your own
            texts (as .txt, .epub, or .pdf files) to read or have simplified, we store that text
            so the service can process and display it back to you. You&apos;re responsible for
            having the right to use and upload that content — see our{' '}
            <a href="/termsOfService" className="text-[#1a1a1a] underline underline-offset-2">
              Terms of Service
            </a>{' '}
            for more on this.
          </p>
          <p className="mb-3">
            <strong className="text-[#1a1a1a]">Usage and learning data.</strong> Words and phrases
            you save as flashcards, your reading progress in each book, and how many characters
            you&apos;ve processed this month (used only to apply the monthly Pro-plan limit).
          </p>
          <p className="mb-3">
            <strong className="text-[#1a1a1a]">Payment data.</strong> If you subscribe to Pro,
            payments are handled entirely by Stripe, our payment processor. We never see or store
            your full card details — we only receive confirmation that a payment succeeded or
            failed, and a Stripe-issued reference we use to manage your subscription.
          </p>
          <p className="mb-3">
            <strong className="text-[#1a1a1a]">Technical data.</strong> Standard technical
            information generated by using a website — for example IP address and browser
            information, handled as part of normal hosting and security operations by our
            infrastructure providers.
          </p>
          <p>
            We do <strong className="text-[#1a1a1a]">not</strong> currently use cookies for
            advertising or tracking, and we don&apos;t currently run any analytics tool. If that
            changes (for example, if we add Google Analytics), we&apos;ll update this policy
            first and, where required, ask for your consent before setting non-essential cookies.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-medium text-[#1a1a1a]">3. Why we process your data, and on what legal basis</h2>
          <div className="space-y-3">
            <div className="rounded-lg border border-[#e7e5e4] bg-white p-4">
              <p className="text-[#1a1a1a]">Create and manage your account</p>
              <p className="mt-1 text-xs text-[#a8a29e]">Legal basis: performance of a contract</p>
            </div>
            <div className="rounded-lg border border-[#e7e5e4] bg-white p-4">
              <p className="text-[#1a1a1a]">Translate words, phrases, and texts you read</p>
              <p className="mt-1 text-xs text-[#a8a29e]">Legal basis: performance of a contract</p>
            </div>
            <div className="rounded-lg border border-[#e7e5e4] bg-white p-4">
              <p className="text-[#1a1a1a]">Process texts you upload (formatting, simplification)</p>
              <p className="mt-1 text-xs text-[#a8a29e]">Legal basis: performance of a contract</p>
            </div>
            <div className="rounded-lg border border-[#e7e5e4] bg-white p-4">
              <p className="text-[#1a1a1a]">Process your Pro subscription payment</p>
              <p className="mt-1 text-xs text-[#a8a29e]">Legal basis: performance of a contract</p>
            </div>
            <div className="rounded-lg border border-[#e7e5e4] bg-white p-4">
              <p className="text-[#1a1a1a]">Enforce monthly usage limits</p>
              <p className="mt-1 text-xs text-[#a8a29e]">Legal basis: legitimate interest</p>
            </div>
            <div className="rounded-lg border border-[#e7e5e4] bg-white p-4">
              <p className="text-[#1a1a1a]">Respond to support requests</p>
              <p className="mt-1 text-xs text-[#a8a29e]">Legal basis: legitimate interest / contract</p>
            </div>
            <div className="rounded-lg border border-[#e7e5e4] bg-white p-4">
              <p className="text-[#1a1a1a]">Keep basic security and technical logs</p>
              <p className="mt-1 text-xs text-[#a8a29e]">Legal basis: legitimate interest</p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-[#1a1a1a]">4. Who we share your data with</h2>
          <p className="mb-3">
            We use a small number of third-party services to run Balaka. Each of them only
            receives the data they need to do their specific job:
          </p>
          <ul className="list-disc space-y-2 pl-5">
            <li><strong className="text-[#1a1a1a]">Supabase</strong> (database, authentication, and file storage) — hosted in the EU. Stores your account data, uploaded texts, saved cards, and reading progress.</li>
            <li><strong className="text-[#1a1a1a]">Vercel</strong> (website hosting) — serves the Balaka website itself.</li>
            <li><strong className="text-[#1a1a1a]">Railway</strong> (text-processing server) — handles the heavier parts of processing longer texts (formatting, simplification, extracting text from epub/PDF files).</li>
            <li><strong className="text-[#1a1a1a]">Stripe</strong> (payments) — processes your subscription payment. We never see your full card number.</li>
            <li><strong className="text-[#1a1a1a]">Anthropic</strong> (Claude AI) — the AI model that powers translations, simplified retellings, and text formatting. The specific text you&apos;re translating or the book content you upload is sent to Anthropic to generate that result. Anthropic is based in the United States; this involves a transfer of data outside the EU/EEA, which we rely on Anthropic&apos;s own data processing terms and Standard Contractual Clauses to safeguard.</li>
          </ul>
          <p className="mt-3">
            We do not sell your personal data, and we do not share it with anyone for advertising
            purposes. If we add new third-party providers in the future (for example, a
            text-to-speech provider for audio features, or an analytics tool), we&apos;ll update
            this section before those features go live.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-[#1a1a1a]">5. How long we keep your data</h2>
          <p>
            We keep your account data and content for as long as your account is active. If you
            ask us to delete your account (see Section 7), we&apos;ll delete your personal data
            and content, except where we&apos;re legally required to keep certain records (for
            example, payment records for tax purposes) or where data remains briefly in routine
            backups.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-[#1a1a1a]">6. International data transfers</h2>
          <p>
            Most of our infrastructure (Supabase) is hosted in the EU. Some of our providers —
            notably Anthropic and Stripe — are based in the United States, which means some of
            your data is transferred outside the EU/EEA when we use their services. We rely on
            the safeguards those providers have in place, including Standard Contractual Clauses,
            to protect your data during these transfers.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-[#1a1a1a]">7. Your rights</h2>
          <p className="mb-3">
            If you&apos;re in the EU/EEA (or covered by similar data protection law elsewhere),
            you have the right to:
          </p>
          <ul className="list-disc space-y-1 pl-5">
            <li><strong className="text-[#1a1a1a]">Access</strong> the personal data we hold about you</li>
            <li><strong className="text-[#1a1a1a]">Correct</strong> inaccurate data</li>
            <li><strong className="text-[#1a1a1a]">Delete</strong> your data (&quot;right to be forgotten&quot;)</li>
            <li><strong className="text-[#1a1a1a]">Restrict or object to</strong> certain processing</li>
            <li><strong className="text-[#1a1a1a]">Data portability</strong> — receive your data in a portable format</li>
          </ul>
          <p className="mt-3 mb-3">
            <strong className="text-[#1a1a1a]">Deleting your account:</strong> at the moment,
            account deletion is handled manually rather than through a self-service button in the
            app. To request deletion of your account and data, please email us at{' '}
            <span className="text-[#a8a29e]">[contact email]</span> and we&apos;ll process your
            request promptly.
          </p>
          <p>
            To exercise any other right, contact us at the email above. If you&apos;re not
            satisfied with how we&apos;ve handled your request, you have the right to complain to
            the Spanish data protection authority (Agencia Española de Protección de Datos,
            AEPD) or your local equivalent.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-[#1a1a1a]">8. Children</h2>
          <p>
            Balaka is not directed at children under 14. In line with Spanish law on digital
            consent, you must be at least 14 years old to create an account. If you believe a
            child under 14 has created an account, please contact us and we will remove it.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-[#1a1a1a]">9. Security</h2>
          <p>
            We take reasonable technical and organizational measures to protect your data,
            including relying on our infrastructure providers&apos; own security practices
            (encryption in transit, access controls, etc.). No online service can guarantee
            complete security, but we take this seriously given the personal nature of the data
            involved.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-[#1a1a1a]">10. Changes to this policy</h2>
          <p>
            We may update this Privacy Policy from time to time, for example as we add new
            features or providers. If we make a material change, we&apos;ll give notice — for
            example by email or a notice on the Service — before it takes effect.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-[#1a1a1a]">11. Contact us</h2>
          <p>
            If you have questions about this policy or how we handle your data, contact us at{' '}
            <span className="text-[#a8a29e]">[contact email]</span>.
          </p>
        </section>

        <p className="border-t border-[#e7e5e4] pt-6 text-xs italic text-[#a8a29e]">
          This policy was drafted to accurately reflect how Balaka currently operates, but it is
          not a substitute for professional legal advice. Given that Balaka processes payments
          and personal data internationally, we recommend a qualified lawyer review this policy
          before it is treated as final, particularly regarding the exact wording required for a
          sole individual (rather than a registered company) acting as data controller under
          Spanish and EU law.
        </p>
      </div>
    </div>
  );
}
